# Standards: 0.11
---

- name: Restart sshd
  service:
    name: sshd
    state: restarted
  when: not in_container

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
  when: not in_container

- name: Restart auditd
  service:
    name: auditd
    state: restarted
  when: not in_container
