# Standards: 2.0.0
---

# 4.1.2 Ensure auditd service is enabled (Scored)
- name: 4.1.2 - Ensure auditd service is enabled (Scored)
  command: yum -q list audit
  ignore_errors: true
  register: auditd
  tags:
    - level-2
    - section-4
    - section-4.2
    - section-4.2.1
    - section-4.2.1.1
    - "4.2.1.1"
    - scored
    - lint  # ANSIBLE0006, ANSIBLE0012

- name: 4.1.2 - Ensure auditd service is enabled (Scored)
  service:
    name: "auditd"
    enabled: true
    state: started
  when:
    - not in_container
    - auditd.rc is not defined or auditd.rc == 0
  tags:
    - level-2
    - section-4
    - section-4.2
    - section-4.2.1
    - section-4.2.1.1
    - "4.2.1.1"
    - scored
