# Standards: 0.11
---

# 1.1.19 - Disable Automounting

- name: 1.1.19 - Disable autofs
  service:
    name: autofs
    enabled: false
    state: stopped
  register: service
  failed_when: service is failed and not 'Could not find the requested service' in service.msg
  when: not in_container
  tags:
    - level-1
    - section-1
    - section-1.1
    - section-1.1.19
    - "1.1.19"
    - scored
