# Standards: 0.11
---

# 1.1.18 Ensure sticky bit is set on all world-writable directories

- name: 1.1.18 - Ensure sticky bit is set on all world-writable directories
  block:
    - name: 1.1.18 - Ensure findutils is installed
      yum:
        name: findutils

    - name: 1.1.18 - Ensure sticky bit is set on all world-writable directories
      shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t"
      register: chmod
      failed_when: chmod is failed and (chmod.stdout_lines | reject('match', 'Read-only file system') | list)
  tags:
    - level-1
    - section-1
    - section-1.1
    - "1.1.18"
    - scored
    - non-idempotent
