# Standards: 0.11
---

# 1.5.2 Ensure XD/NX support is enabled

- name: 1.5.2 - Check if XD/NX support is enabled
  shell: "dmesg | grep NX"
  register: dmesg
  check_mode: false
  changed_when: false
  ignore_errors: true
  tags:
    - level-1
    - section-1
    - section-1.5
    - section-1.5.2
    - "1.5.2"
    - not-scored

- name: 1.5.2 - Ensure XD/NX support is enabled
  fail:
    msg: "Ensure XD/NX support is enabled."
  when:
    - "'NX (Execute Disable) protection: active' not in dmesg.stdout"
    - fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-1
    - section-1.5
    - section-1.5.2
    - "1.5.2"
    - not-scored

- name: 1.5.2 - Ensure XD/NX support is enabled
  debug:
    msg: "*** ACTION REQUIRED *** Ensure XD/NX support is enabled."
  when:
    - "'NX (Execute Disable) protection: active' not in dmesg.stdout"
    - not fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-1
    - section-1.5
    - section-1.5.2
    - "1.5.2"
    - not-scored
