# Standards: 0.11
---

# 1.5.3 Ensure address space layout randomization (ASLR) is enabled

- name: 1.5.3 - Ensure address space layout randomization is enabled
  sysctl:
    ignoreerrors: true
    name: kernel.randomize_va_space
    value: 2
    state: present
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-1
    - section-1.5
    - "1.5.3"
    - scored
