# Standards: 0.11
---

# 1.5.3 Ensure address space layout randomization (ASLR) is enabled

- name: 1.5.3 - Ensure address space layout randomization is enabled
  sysctl:
    name: kernel.randomize_va_space
    value: 2
  when: not in_container
  tags:
    - level-1
    - section-1
    - section-1.5
    - section-1.5.3
    - "1.5.3"
    - scored
