# Standards: 0.11
---

# 2.1.2 Ensure daytime services are not enabled

- name: 2.1.2 - Ensure daytime services are not enabled
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
    - daytime-dgram
    - daytime-stream
  register: service
  failed_when: service is failed and not 'Could not find the requested service' in service.msg
  when: not in_container
  tags:
    - level-1
    - section-2
    - section-2.1
    - section-2.1.2
    - "2.1.2"
    - scored
