# Standards: 0.11
---

# 2.1.3 Ensure discard services are not enabled

- name: 2.1.3 - Ensure discard services are not enabled
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
    - discard-dgram
    - discard-stream
  register: service
  failed_when: service is failed and not 'Could not find the requested service' in service.msg
  when: not in_container
  tags:
    - level-1
    - section-2
    - section-2.1
    - section-2.1.3
    - "2.1.3"
    - scored
