# Standards: 0.11
---

# 2.1.8 Ensure telnet server is not enabled

- name: 2.1.8 - Ensure telnet server is not enabled
  service:
    name: "telnet"
    enabled: false
    state: stopped
  register: service
  failed_when: service is failed and not 'Could not find the requested service' in service.msg
  when: not in_container
  tags:
    - level-1
    - section-2
    - section-2.1
    - section-2.1.8
    - "2.1.8"
    - scored
