# Standards: 2.0.0
---

# 2.1.10 Ensure rsync server is not enabled

- name: 2.1.10 - Ensure rsync server is not enabled
  service:
    name: "rsync"
    enabled: false
    state: stopped
  register: service
  failed_when: service is failed and not 'Could not find the requested service' in service.msg
  when: not in_container
  tags:
    - level-1
    - section-2
    - section-2.1
    - section-2.1.10
    - "2.1.10"
    - scored
