# Standards: 2.0.0
---

# 2.2.4 Ensure CUPS is not enabled

- name: 2.2.4 - Ensure CUPS is not enabled
  service:
    name: "cups"
    enabled: false
    state: stopped
  register: service
  failed_when: service is failed and not 'Could not find the requested service' in service.msg
  when: not in_container
  tags:
    - level-1
    - section-2
    - section-2.2
    - section-2.2.4
    - "2.2.4"
    - scored
