# Standards: 2.0.0
---

# 2.2.2 Ensure X Window System is not installed

- name: 2.2.2 - Ensure X Window System is not installed
  yum:
    name: "xorg-x11*"
    state: absent
  tags:
    - level-1
    - section-2
    - section-2.2
    - section-2.2.2
    - "2.2.2"
    - scored
