# Standards: 0.11
---

# 2.2.8 Ensure DNS Server is not enabled

- name: 2.2.8 - Ensure DNS Server is not enabled
  service:
    name: "named"
    enabled: false
    state: stopped
  ignore_errors: true
  tags:
    - level-1
    - section-2
    - section-2.2
    - section-2.2.8
    - "2.2.8"
    - scored
