# Standards: 0.11
---

# 2.2.10 Ensure HTTP server is not enabled

- name: 2.2.10 - Ensure HTTP server is not enabled
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
    - httpd
    - apache
    - apache2
    - nginx
    - lighttpd
  register: service
  failed_when: service is failed and not 'Could not find the requested service' in service.msg
  when: not in_container
  tags:
    - level-1
    - section-2
    - section-2.2
    - section-2.2.10
    - "2.2.10"
    - scored
