# Standards: 0.11
---

# 2.2.6 Ensure LDAP server is not enabled

- name: 2.2.6 - Ensure LDAP server is not enabled
  service:
    name: "slapd"
    enabled: false
    state: stopped
  ignore_errors: true
  tags:
    - level-1
    - section-2
    - section-2.2
    - section-2.2.6
    - "2.2.6"
    - scored
