# Standards: 0.11
---

# 2.2.14 Ensure SNMP Server is not enabled

- name: 2.2.14 - Ensure SNMP Server is not enabled
  service:
    name: "snmpd"
    enabled: false
    state: stopped
  register: service
  failed_when: service is failed and not 'Could not find the requested service' in service.msg
  when: not in_container
  tags:
    - level-1
    - section-2
    - section-2.2
    - section-2.2.14
    - "2.2.14"
    - scored
