# Standards: 2.0.0
---

# 2.2.3 Ensure Avahi Server is not enabled

- name: 2.2.3 - Ensure Avahi Server is not enabled
  service:
    name: "avahi-daemon"
    enabled: false
    state: stopped
  register: service
  failed_when: service is failed and not 'Could not find the requested service' in service.msg
  when: not in_container
  tags:
    - level-1
    - section-2
    - section-2.2
    - section-2.2.3
    - "2.2.3"
    - scored
