# Standards: 2.0.0
---

# 2.2.7 Ensure NFS and RPC are not enabled

- name: 2.2.7 - Ensure NFS and RPC are not enabled
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
    - nfs
    - rpcbind
  register: service
  failed_when: service is failed and not 'Could not find the requested service' in service.msg
  when: not in_container
  tags:
    - level-1
    - section-2
    - section-2.2
    - section-2.2.7
    - "2.2.7"
    - scored
