# Standards: 2.0.0
---

# 2.3.5 Ensure LDAP client is not installed

- name: 2.3.5 - Ensure LDAP client is not installed
  yum:
    name: "openldap-clients"
    state: absent
  tags:
    - level-1
    - section-2
    - section-2.3
    - section-2.3.5
    - "2.3.5"
    - scored
