# Standards: 0.11
---

# 3.1.2 Ensure packet redirect sending is disabled

- name: 3.1.2 - Ensure packet redirect sending is disabled
  sysctl:
    ignoreerrors: true
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict:
    "net.ipv4.conf.all.send_redirects": 0
    "net.ipv4.conf.default.send_redirects": 0
    "net.ipv4.route.flush": 1
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-3
    - section-3.1
    - "3.1.2"
    - scored
