# Standards: 0.11
---

# 3.1.1 Ensure IP forwarding is disabled

- name: 3.1.1 - Ensure IP forwarding is disabled in active kernel parameters
  sysctl:
    ignoreerrors: true
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict:
    "net.ipv4.ip_forward": 0
    "net.ipv4.route.flush": 1
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-3
    - section-3.1
    - "3.1.1"
    - scored
