# Standards: 0.11
---

# 3.2.1 Ensure source routed packets are not accepted

- name: 3.2.1 - Ensure source routed packets are not accepted
  sysctl:
    ignoreerrors: true
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict:
    "net.ipv4.conf.all.accept_source_route": 0
    "net.ipv4.conf.default.accept_source_route": 0
    "net.ipv4.route.flush": 1
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-3
    - section-3.2
    - "3.2.1"
    - scored
