# Standards: 0.11
---

# 3.2.5 Ensure broadcast ICMP requests are ignored

- name: 3.2.5 - Ensure broadcast ICMP requests are ignored
  sysctl:
    ignoreerrors: true
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict:
    "net.ipv4.icmp_echo_ignore_broadcasts": 1
    "net.ipv4.route.flush": 1
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-3
    - section-3.2
    - section-3.2.5
    - "3.2.5"
    - scored
