# Standards: 0.11
---

# 3.2.8 Ensure TCP SYN Cookies is enabled

- name: 3.2.8 - Ensure TCP SYN Cookies is enabled
  sysctl:
    ignoreerrors: true
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict:
    "net.ipv4.tcp_syncookies": 1
    "net.ipv4.route.flush": 1
  when: not in_container
  tags:
    - level-1
    - section-3
    - section-3.2
    - section-3.2.8
    - "3.2.8"
    - scored
