# Standards: 2.0.0
---

# 3.3.3 Ensure IPv6 is disabled

- name: 3.3.3 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe
  tags:
    - level-1
    - section-3
    - section-3.3
    - section-3.3.3
    - "3.3.3"
    - scored

- name: 3.3.3 - Ensure IPv6 is disabled
  copy:
    dest: "{{ cis_modprobe_conf_filename }}"
    content: "options ipv6 disable=1\n"
  when: modprobe.stat.exists is not defined or not modprobe.stat.exists
  tags:
    - level-1
    - section-3
    - section-3.3
    - section-3.3.3
    - "3.3.3"
    - scored

- name: 3.3.3 - Ensure IPv6 is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^options ipv6 disable="
    line: "options ipv6 disable=1"
  when: modprobe.stat.exists is defined and modprobe.stat.exists
  tags:
    - level-1
    - section-3
    - section-3.3
    - section-3.3.3
    - "3.3.3"
    - scored
