# Standards: 0.11
---

# 3.3.1 Ensure IPv6 router advertisements are not accepted

- name: 3.3.1 - Ensure IPv6 router advertisements are not accepted
  sysctl:
    ignoreerrors: true
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict:
    "net.ipv6.conf.all.accept_ra": 0
    "net.ipv6.conf.default.accept_ra": 0
    "net.ipv4.route.flush": 1
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  ignore_errors: true
  tags:
    - level-1
    - section-3
    - section-3.3
    - "3.3.1"
    - scored
