# Standards: 0.11
---

# 3.4.1 Ensure TCP Wrappers is installed

- name: 3.4.1 - Ensure TCP Wrappers is installed
  yum:
    name: tcp_wrappers
  tags:
    - level-1
    - section-3
    - section-3.4
    - "3.4.1"
    - scored
