# Standards: 0.11
---

# 3.6.4 Ensure outbound and established connections are configured

- name: 3.6.4 - Ensure outbound and established connections are configured
  iptables:
    chain: OUTPUT
    protocol: tcp
    match: state
    ctstate: ESTABLISHED,NEW
    jump: ACCEPT
  become: true
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-3
    - section-3.6
    - "3.6.4"
    - not-scored

- name: 3.6.4 - Ensure outbound and established connections are configured
  iptables:
    chain: OUTPUT
    protocol: udp
    match: state
    ctstate: ESTABLISHED,NEW
    jump: ACCEPT
  become: true
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-3
    - section-3.6
    - "3.6.4"
    - not-scored

- name: 3.6.4 - Ensure outbound and established connections are configured
  iptables:
    chain: OUTPUT
    protocol: icmp
    match: state
    ctstate: ESTABLISHED,NEW
    jump: ACCEPT
  become: true
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-3
    - section-3.6
    - "3.6.4"
    - not-scored

- name: 3.6.4 - Ensure outbound and established connections are configured
  iptables:
    chain: INPUT
    protocol: tcp
    match: state
    ctstate: ESTABLISHED
    jump: ACCEPT
  become: true
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-3
    - section-3.6
    - "3.6.4"
    - not-scored

- name: 3.6.4 - Ensure outbound and established connections are configured
  iptables:
    chain: INPUT
    protocol: udp
    match: state
    ctstate: ESTABLISHED
    jump: ACCEPT
  become: true
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-3
    - section-3.6
    - "3.6.4"
    - not-scored

- name: 3.6.4 - Ensure outbound and established connections are configured
  iptables:
    chain: INPUT
    protocol: icmp
    match: state
    ctstate: ESTABLISHED
    jump: ACCEPT
  become: true
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-3
    - section-3.6
    - "3.6.4"
    - not-scored
