# Standards: 0.11
---

# 3.6.2 Ensure default deny firewall policy

- name: 3.6.2 - Ensure default deny firewall policy(DROP INPUT)
  iptables:
    chain: "{{item}}"
    policy: DROP
  become: true
  with_items:
    - INPUT
    - FORWARD
    - OUTPUT
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-3
    - section-3.6
    - section-3.6.2
    - "3.6.2"
    - scored
