# Standards: 0.11
---

# 3.6.3 Ensure loopback traffic is configured

- name: 3.6.3 - Ensure loopback traffic is configured(-i lo)
  iptables:
    chain: INPUT
    in_interface: "lo"
    jump: ACCEPT
  become: true
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-3
    - section-3.6
    - section-3.6.3
    - "3.6.3"
    - scored

- name: 3.6.3 - Ensure loopback traffic is configured(-o lo)
  iptables:
    chain: OUTPUT
    out_interface: "lo"
    jump: ACCEPT
  become: true
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-3
    - section-3.6
    - section-3.6.3
    - "3.6.3"
    - scored

- name: 3.6.3 - Ensure loopback traffic is configured(-i 127.0.0.1/8)
  iptables:
    chain: INPUT
    source: 127.0.0.0/8
    jump: DROP
  become: true
  when: >
    ansible_virtualization_role is undefined or
    not (ansible_virtualization_role == 'guest' and ansible_virtualization_type in ['lxc', 'docker'])
  tags:
    - level-1
    - section-3
    - section-3.6
    - section-3.6.3
    - "3.6.3"
    - scored
