# Standards: 2.0.0
---

# 4.2.2.1 Ensure syslog-ng service is enabled

- name: 4.2.2.1 - Check if syslog-ng is installed
  command: yum -q list syslog-ng
  ignore_errors: true
  register: syslog_ng
  when: cis_enable_syslog_ng
  tags:
    - level-1
    - section-4
    - section-4.2
    - section-4.2.2
    - section-4.2.2.1
    - "4.2.2.1"
    - scored
    - lint  # ANSIBLE0006

- name: 4.2.2.1 - Ensure syslog-ng service is enabled
  service:
    name: "syslog-ng"
    enabled: true
    state: started
  when:
    - not in_container
    - cis_enable_syslog_ng
    - syslog_ng is defined
    - syslog_ng.rc is not defined or syslog_ng.rc == 0
  tags:
    - level-1
    - section-4
    - section-4.2
    - section-4.2.2
    - section-4.2.2.1
    - "4.2.2.1"
    - scored
