# Standards: 0.11
---

# 4.2.1.1 Ensure rsyslog Service is enabled

- name: 4.2.1.1 - Check if rsyslog is installed
  command: yum -q list rsyslog
  ignore_errors: true
  when: cis_enable_rsyslog
  register: rsyslog
  tags:
    - level-1
    - section-4
    - section-4.2
    - section-4.2.1
    - section-4.2.1.1
    - "4.2.1.1"
    - scored
    - non-idempotent
    - lint  # ANSIBLE0006

- name: 4.2.1.1 - Ensure rsyslog Service is enabled
  service:
    name: "rsyslog"
    enabled: true
    state: started
  when:
    - not in_container
    - cis_enable_rsyslog
    - rsyslog.rc is not defined or rsyslog.rc == 0
  tags:
    - level-1
    - section-4
    - section-4.2
    - section-4.2.1
    - section-4.2.1.1
    - "4.2.1.1"
    - scored
